logging:
  level:
    root: info
    ru: debug
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://5.42.220.205:3306/default_db
    username: gen_user
    password: \vBB!,]]*98sc)
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template-location: false
server:
  port: 8080


