logging:
  level:
    root: info
    ru: debug
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://81.200.145.234:3306/Cinema
    username: user
    password: qwerty123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template-location: false
server:
  port: 8080


